language: cpp
branches:
  only:
  - task10
before_script:
  - mkdir build
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7
  - cd build
  - cmake ..
  - cmake --build .
  - sudo env "PATH=$PATH" cmake --build . --target test
  - seq 0 1000 | ./bin/bulkmt 10
  - cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: task10
    script:
    - curl -T bulkmt-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -umkvdv:$BINTRAY_API_KEY "https://api.bintray.com/content/mkvdv/otus10/bulkmt/0.0.$TRAVIS_BUILD_NUMBER/bulkmt-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
