language: cpp
compiler: clang
env:
  global:
    - VERSION_MAJOR=1
    - VERSION_MINOR=0
before_script:
  - mkdir build
addons:
  apt:
    packages:
      - libboost-all-dev
script:
  - cd build
  - cmake ..
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: task01
  script:
    - curl -T hello_world-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -umkvdv:$BINTRAY_API_KEY "https://api.bintray.com/content/mkvdv/otus-cpp-2018/ha/$TRAVIS_BUILD_NUMBER/hello_world-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
