language: cpp
branches:
  only:
    - task05
before_script:
  - mkdir build
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - doxygen
      - graphviz
script:
  - doxygen Doxyfile
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7
  - cd build
  - cmake ..
  - cmake --build .
  - sudo env "PATH=$PATH" cmake --build . --target test
  - cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    on:
        branch: task05
    script:
    - curl -T cpp_05-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -umkvdv:$BINTRAY_API_KEY "https://api.bintray.com/content/mkvdv/otus05/cpp_05/0.0.$TRAVIS_BUILD_NUMBER/cpp_05-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

  - provider: pages
    skip_cleanup: true
    local_dir: docs/html
    github_token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: task05