dist: xenial
language: cpp
env:
  global:
    - VERSION_MAJOR=1
    - VERSION_MINOR=0
branches:
  only:
    - task11
before_script:
  - mkdir build
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7
  - cd build
  - cmake ..
  - cmake --build .
  - ./bin/async_cli
  - sudo env "PATH=$PATH" cmake --build . --target test
  - cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: task11
    script:
      - curl -T async_cli-$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER-Linux.deb -umkvdv:$BINTRAY_API_KEY "https://api.bintray.com/content/mkvdv/otus-cpp-2018/ha/async_cli/$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER/async_cli-$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

