dist: xenial
language: cpp
compiler:
  - clang
env:
  global:
    - VERSION_MAJOR=1
    - VERSION_MINOR=0
branches:
  only:
    - task07
before_script:
  - mkdir build
script:
  - cd build
  - cmake ..
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: task07
    script:
      - curl -T bulk-$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER-Linux.deb -umkvdv:$BINTRAY_API_KEY "https://api.bintray.com/content/mkvdv/otus-cpp-2018/ha/bulk/$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER/bulk-$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
