dist: xenial
language: cpp
compiler:
  - clang
branches:
  only:
    - task08_2
before_script:
  - mkdir build
  - sudo apt update
addons:
  apt:
    packages:
      - libboost-all-dev
      - libssl-dev
script:
  - cd build
  - cmake ..
  - cmake --build .
  - cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: task08_2
    script:
      - curl -T bayan-$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER-Linux.deb -umkvdv:$BINTRAY_API_KEY "https://api.bintray.com/content/mkvdv/otus-cpp-2018/ha/bayan/$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER/bayan-$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
