dist: xenial
language: cpp
compiler: clang
env:
  global:
    - VERSION_MAJOR=1
    - VERSION_MINOR=0
before_script:
  - mkdir build
script:
  - cmake -H. -Bbuild -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release
  - cmake --build build
  - cmake --build build --target test
  - cmake --build build --target package
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: task02
  script:
    - curl -T ./build/ip_filter-$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER-Linux.deb -umkvdv:$BINTRAY_API_KEY "https://api.bintray.com/content/mkvdv/otus-cpp-2018/ha/ip_filter/$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER/ip_filter-$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
