dist: xenial
language: cpp
compiler:
  - clang
env:
  global:
    - VERSION_MAJOR=1
    - VERSION_MINOR=0
branches:
  only:
    - task05
before_script:
  - mkdir build
addons:
  apt:
    packages:
      - doxygen
      - graphviz
script:
  - doxygen Doxyfile
  - cd build
  - cmake ..
  - cmake --build .
  - sudo env "PATH=$PATH" cmake --build . --target test
  - cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: task05
    script:
      - curl -T editor-$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER-Linux.deb -umkvdv:$BINTRAY_API_KEY "https://api.bintray.com/content/mkvdv/otus-cpp-2018/ha/editor/$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER/editor-$VERSION_MAJOR.$VERSION_MINOR.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

  - provider: pages
    skip_cleanup: true
    local_dir: docs/html
    github_token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: task05