dist: xenial
language: cpp
before_script:
  - mkdir build
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7
  - cmake -H. -Bbuild -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release
  - cmake --build build
  - cmake --build build --target test
  - cmake --build build --target package
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: task02
  script:
    - pwd
    - ls
    - curl -T build/cpp_02-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -umkvdv:$BINTRAY_API_KEY "https://api.bintray.com/content/mkvdv/otus02/cpp_02/0.0.$TRAVIS_BUILD_NUMBER/cpp_02-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
