language: cpp
before_script:
  - mkdir build
script:
  - cd build
  - cmake ..
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  on:
      branch: task01
  script:
  - curl -T cpp_01_gtest-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -umkvdv:$BINTRAY_API_KEY "https://api.bintray.com/content/mkvdv/otus01_gtest/cpp_01_gtest/0.0.$TRAVIS_BUILD_NUMBER/cpp_01_gtest-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
